import os
import io
import uvicorn
from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.responses import StreamingResponse, Response
from fastapi.middleware.cors import CORSMiddleware
import google.generativeai as genai
from xhtml2pdf import pisa

app = FastAPI()

# --- CONFIGURATION ---
# 1. Allow Frontend to talk to Backend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows Netlify to connect
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 2. Setup Google AI
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
if not GOOGLE_API_KEY:
    print("WARNING: GOOGLE_API_KEY not found in environment variables!")

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

# --- LOGIC ---

async def stream_gemini(prompt_text, image_parts=None):
    """Helper to stream AI response chunk by chunk"""
    try:
        input_data = [prompt_text]
        if image_parts:
            input_data.extend(image_parts)

        # Ask AI with streaming enabled
        response = model.generate_content(input_data, stream=True)
        
        for chunk in response:
            if chunk.text:
                # Format for Server-Sent Events (data: text\n\n)
                clean_text = chunk.text.replace("\n", "\\n")
                yield f"data: {clean_text}\n\n"
                
    except Exception as e:
        yield f"data: [ERROR] {str(e)}\n\n"

@app.post("/chat")
async def chat_endpoint(
    prompt: str = Form(...),
    files: list[UploadFile] = File(None)
):
    """Receives text + images, streams back the AI response"""
    image_parts = []
    
    # 1. Handle Image Uploads
    if files:
        for file in files:
            content = await file.read()
            if file.content_type.startswith('image/'):
                image_parts.append({
                    "mime_type": file.content_type,
                    "data": content
                })

    # 2. System Instructions for AI
    system_instruction = """
    You are a professional document writer.
    1. Format your response using HTML tags ONLY (e.g., <h1>Title</h1>, <p>text</p>, <b>bold</b>, <ul><li>item</li></ul>).
    2. Do NOT use markdown (like ** or ##).
    3. If the user provides an image, analyze it and include relevant details in the document.
    4. Keep the tone professional.
    """
    
    full_prompt = f"{system_instruction}\n\nUser Request: {prompt}"

    return StreamingResponse(stream_gemini(full_prompt, image_parts), media_type="text/event-stream")

@app.post("/generate-pdf")
async def generate_pdf(html_content: str = Form(...)):
    """Converts the AI's HTML output into a PDF file"""
    try:
        # Add basic CSS styles for the PDF
        full_html = f"""
        <html>
        <head>
            <style>
                @page {{ size: A4; margin: 2cm; }}
                body {{ font-family: Helvetica, sans-serif; color: #333; line-height: 1.5; }}
                h1 {{ color: #2563eb; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
                h2 {{ color: #475569; margin-top: 20px; }}
                p {{ margin-bottom: 10px; text-align: justify; }}
                ul {{ margin-bottom: 10px; }}
                .footer {{ font-size: 10px; color: #888; text-align: center; margin-top: 50px; }}
            </style>
        </head>
        <body>
            {html_content}
            <div class="footer">Generated by AI Doc Maker</div>
        </body>
        </html>
        """
        
        # Convert to PDF
        pdf_buffer = io.BytesIO()
        pisa_status = pisa.CreatePDF(io.StringIO(full_html), dest=pdf_buffer)

        if pisa_status.err:
            raise HTTPException(status_code=500, detail="PDF conversion failed")

        pdf_buffer.seek(0)
        
        return Response(content=pdf_buffer.read(), media_type="application/pdf", headers={
            "Content-Disposition": "attachment; filename=ai_document.pdf"
        })

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
